linters:
  Comment:
    exclude: 'app/assets/stylesheets/application.scss'
  ColorVariable:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  ImportantRule:
    enabled: false
  SelectorDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  NestingDepth:
    max_depth: 5
